apiVersion: machine.openshift.io/v1beta1
kind: MachineHealthCheck
metadata:
  name: srep-worker-healthcheck
  namespace: openshift-machine-api
spec:
  selector:
    matchExpressions:
    - key: machine.openshift.io/cluster-api-machine-role
      operator: NotIn
      values:
      - "infra"
      - "master"
    - key: machine.openshift.io/cluster-api-machineset
      operator: Exists
  unhealthyConditions:
  - type:    "Ready"
    timeout: "480s"
    status: "False"
  - type:    "Ready"
    timeout: "480s"
    status: "Unknown"
  maxUnhealthy: 3
  nodeStartupTimeout: 25m
