apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: osd-sre-admin
rules:
# SRE can get, list, and watch all resources
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
# SRE can manage nodes
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - patch
# SRE can evict pods
- apiGroups:
  - ""
  resources:
  - pods/eviction
  verbs:
  - create
  # SRE can run commands in pods
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - create
# SRE can delete jobs and builds
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - delete
  - deletecollection
- apiGroups:
  - build.openshift.io
  resources:
  - builds
  verbs:
  - delete
  - deletecollection
# SRE can manage projects
- apiGroups:
  - config.openshift.io
  resources:
  - projects
  verbs:
  - '*'
- apiGroups:
  - project.openshift.io
  resources:
  - projects
  verbs:
  - '*'
# SRE can manage namespaces
- apiGroups:
  - ""
  resources:
  - namespaces
  - namespaces/finalize
  verbs:
  - '*'
# SRE can use oc debug
- apiGroups:
  - ""
  resources:
  - pods
  - pods/attach
  verbs:
  - create
# SRE can delete pods
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - delete
# SRE can review pod security policies
- apiGroups:
  - security.openshift.io
  resources:
  - podsecuritypolicyreviews
  - podsecuritypolicyselfsubjectreviews
  - podsecuritypolicysubjectreviews
  verbs:
  - create
# SRE can update existing groups
- apiGroups:
  - user.openshift.io
  resources:
  - groups
  verbs:
  - patch
  - update
# SRE can upgrade the cluster
- apiGroups:
  - config.openshift.io
  resources:
  - clusterversions
  verbs:
  - patch
  - update
# SRE can review RBAC policies (i.e. oc adm policy who-can ...)
- apiGroups:
  - authorization.openshift.io
  resources:
  - localresourceaccessreviews
  - resourceaccessreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  - authorization.openshift.io
  resources:
  - localsubjectaccessreviews
  - subjectaccessreviews
  verbs:
  - create
# SRE can get and post to all endpoints
- nonResourceURLs:
  - '*'
  verbs:
  - '*'
# SRE can manage Logging (ClusterLogging and ElasticSearch CRs)
- apiGroups:
  - logging.openshift.io
  resources:
  - '*'
  verbs:
  - '*'
# SRE can approve Certificate Signing Requests (CSR)
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests/approval
  verbs:
  - update
# SRE can download backups, review logs, and create backup
- apiGroups:
  - velero.io
  resources:
  - backups
  verbs:
  - create
- apiGroups:
  - velero.io
  resources:
  - deletebackuprequests
  - downloadrequests
  - serverstatusrequests
  verbs:
  - '*'
# SRE can temporarily elevate to cluster-admin by patching osd-sre-cluster-admins clusterrolebinding
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  verbs:
  - bind
  - escalate
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  resourceNames:
  - osd-sre-cluster-admins
  verbs:
  - patch
