apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backplane-mtsre-ocs-consumer-cr-admins
rules:
  - apiGroups:
    - "ocs.openshift.io"
    resources:
      - "storageclassclaims"
      - "storageconsumers"
    verbs:
      - get
      - list
      - watch
      - patch
      - update
  - apiGroups:
    - "noobaa.io"
    resources:
      - "noobaaaccounts"
    verbs:
      - get
      - list
      - watch
      - patch
      - update
  - apiGroups:
    - "ceph.rook.io"
    resources:
      - "cephbucketnotifications"
      - "cephbuckettopics"
      - "cephfilesystemsubvolumegroups"
    verbs:
      - get
      - list
      - watch
      - patch
      - update
  - apiGroups:
    - "csiaddons.openshift.io"
    resources:
      - "csiaddonsnodes"
      - "networkfences"
      - "reclaimspacecronjobs"
      - "reclaimspacejobs"
    verbs:
      - get
      - list
      - watch
      - patch
      - update
