apiVersion: managed.openshift.io/v1alpha1
kind: SubjectPermission
metadata:
  name: backplane-mtsre-ocs-consumer-admins
  namespace: openshift-rbac-permissions
spec:
  permissions:
  - allowFirst: true
    clusterRoleName: admin
    namespacesAllowedRegex: (^openshift-storage$)
  subjectKind: Group
  subjectName: system:serviceaccounts:openshift-backplane-mtsre
