apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: backplane-lpsre-ocp-monitoring-project
  namespace: openshift-monitoring
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:serviceaccounts:openshift-backplane-lpsre
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: backplane-lpsre-ocp-monitoring-project
