apiVersion: cloudcredential.openshift.io/v1beta1
kind: CredentialsRequest
metadata:
  name: sre-ebs-iops-reporter-aws-credentials
  namespace: openshift-monitoring
spec:
  secretRef:
    name: sre-ebs-iops-reporter-aws-credentials
    namespace: openshift-monitoring
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1beta1
    kind: AWSProviderSpec
    statementEntries:
    - effect: Allow
      action:
      - cloudwatch:ListMetrics
      - cloudwatch:GetMetricData
      resource: "*"
