deploymentMode: SelectorSyncSet
selectorSyncSet:
  matchExpressions:
  - key: hive.openshift.io/version-major-minor
    operator: In
    values: ["4.16"]
  - key: api.openshift.com/gate-sts <<<<
    operator: In <<<
    values: ["4.17"] <<<
  - key: api.openshift.com/sts
    operator: In
    values: ["true"]
