apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: backplane-srep-opentelemetry
  namespace: openshift-opentelemetry-operator
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:serviceaccounts:openshift-backplane-srep
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: backplane-srep-opentelemetry
