apiVersion: managed.openshift.io/v1alpha1
kind: SubjectPermission
metadata:
  name: backplane-acs-admins-project
  namespace: openshift-rbac-permissions
spec:
  permissions:
  - clusterRoleName: view
    namespacesAllowedRegex: (^redhat-acs-fleetshard$|^rhacs$|^rhacs-.*)
    namespacesDeniedRegex: openshift-backplane-cluster-admin
  - clusterRoleName: backplane-acs-admins-project
    namespacesAllowedRegex: (^redhat-acs-fleetshard$|^rhacs$|^rhacs-.*)
    namespacesDeniedRegex: openshift-backplane-cluster-admin
  subjectKind: Group
  subjectName: system:serviceaccounts:openshift-backplane-acs
