apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: backplane-acs-ingress
  namespace: openshift-ingress
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:serviceaccounts:openshift-backplane-addon-acs-fleet-shard
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: backplane-acs-ingress
