apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: backplane-acs-rhacs-observability
  namespace: rhacs-observability
rules:
# ACS SRE can vew monitoring resources
- apiGroups:
  - monitoring.coreos.com
  resources:
  - alertmanagerconfigs
  - alertmanagers
  - podmonitors
  - probes
  - prometheuses
  - prometheusrules
  - servicemonitors
  - thanosrulers
  verbs:
  - get
  - list
  - watch
# ACS SRE can view observabilities
- apiGroups:
  - observability.redhat.com
  resources:
  - observabilities
  verbs:
  - get
  - list
  - watch
# ACS SRE can view grafanas
- apiGroups:
  - integreatly.org
  resources:
  - grafanas
  - grafanadatasources
  - grafanadashboards
  verbs:
  - get
  - list
  - watch
# ACS SRE can patch persistentvolumeclaims
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - patch
# ACS SRE can restart statefulsets
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - patch
# ACS SRE can view grafana-admin-credentials secret
- apiGroups:
  - ""
  resources:
  - secrets
  resourceNames:
  - grafana-admin-credentials
  verbs:
  - get
  - list
  - watch