apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: sre-router-health
    role: alert-rules
  name: sre-router-health
spec:  
  groups:
  - name: sre-router-health
    rules:
    - alert: RouterAvailabilityLT50Pct
      expr: |
        (sum(avg_over_time(kube_replicationcontroller_status_ready_replicas[1h])) by (replicationcontroller,namespace) 
        /
        on(replicationcontroller,namespace)
        max(kube_replicationcontroller_status_replicas{namespace="default",replicationcontroller=~"router.?-.*"} >0) by (replicationcontroller,namespace)) < 0.5
      labels:
        severity: warn
    - alert: RouterAvailabilityLT30Pct
      expr: |
        (sum(avg_over_time(kube_replicationcontroller_status_ready_replicas[1h])) by (replicationcontroller,namespace) 
        /
        on(replicationcontroller,namespace)
        max(kube_replicationcontroller_status_replicas{namespace="default",replicationcontroller=~"router.?-.*"} >0) by (replicationcontroller,namespace)) < 0.3
      labels:
        severity: critical