deploymentMode: SelectorSyncSet
selectorSyncSet:
  matchExpressions:
    - key: api.openshift.com/fedramp
      operator: In
      values:
        - "true"
    - key: ext-managed.openshift.io/hive-shard
      operator: In
      values:
        - "true"        
