# Source: https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/51d19a433dcfc47fbb7b7a0e1c8ff6ab98ce87e9/deploy/kubernetes/base/csidriver.yaml
kind: CSIDriver
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: efs.csi.aws.com
spec:
  attachRequired: false
