apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backplane-srep-service-cluster-project
rules:
- apiGroups:
  - work.open-cluster-management.io
  resources:
  - appliedmanifestworks
  - operator
  - work
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cluster.open-cluster-management.io
  resources:
  - clusterclaims
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.open-cluster-management.io
  resources:
  - klusterlets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - policy.open-cluster-management.io
  resources:
  - policies
  - configurationpolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - hypershift.openshift.io
  resources:
  - awsendpointservices
  - hostedclusters
  - hostedcontrolplanes
  - nodepools
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cluster.x-k8s.io
  resources:
  - clusterclasses
  - clusters
  - machinedeployments
  - machinehealthchecks
  - machinepools
  - machines
  - machinesets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - awsclustercontrolleridentities
  - awsclusterroleidentities
  - awsclusters
  - awsclusterstaticidentities
  - awsclustertemplates
  - awsfargateprofiles
  - awsmachinepools
  - awsmachines
  - awsmachinetemplates
  - awsmanagedmachinepools
  - azureclusteridentities
  - azureclusters
  - azuremachines
  - azuremachinetemplates
  - ibmpowervsclusters
  - ibmpowervsimages
  - ibmpowervsmachines
  - ibmpowervsmachinetemplates
  - ibmvpcclusters
  - ibmvpcmachines
  - ibmvpcmachinetemplates
  - kubevirtclusters
  - kubevirtmachines
  - kubevirtmachinetemplates
  verbs:
  - get
  - list
  - watch
