---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sre-stuck-ebs-vols
  namespace: openshift-monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sre-stuck-ebs-vols
  namespace: openshift-monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: ServiceAccount
  name: sre-stuck-ebs-vols
  namespace: openshift-monitoring
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sre-allow-read-machine-info
rules:
- apiGroups: ["machine.openshift.io"]
  resources: ["machines"]
  verbs: ["get", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sre-stuck-ebs-vols-read-machine-info
  namespace: openshift-machine-api
subjects:
- kind: ServiceAccount
  name: sre-stuck-ebs-vols
  namespace: openshift-monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sre-allow-read-machine-info
