deploymentMode: "SelectorSyncSet"
selectorSyncSet:
  matchExpressions:
    - key: hive.openshift.io/version-major-minor
      operator: In
      values: ["4.6", "4.7", "4.8"]
    - key: api.openshift.com/environment
      operator: NotIn
      values: ["production"]
