---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
    annotations:
        policy.open-cluster-management.io/categories: CM Configuration Management
        policy.open-cluster-management.io/controls: CM-2 Baseline Configuration
        policy.open-cluster-management.io/standards: NIST SP 800-53
    name: rbac-permissions-operator-config-sp
    namespace: openshift-acm-policies
spec:
    disabled: false
    policy-templates:
        - objectDefinition:
            apiVersion: policy.open-cluster-management.io/v1
            kind: ConfigurationPolicy
            metadata:
                name: rbac-permissions-operator-config-sp
            spec:
                evaluationInterval:
                    compliant: 2m
                    noncompliant: 45s
                object-templates:
                    - complianceType: mustonlyhave
                      metadataComplianceType: musthave
                      objectDefinition:
                        apiVersion: rbac.authorization.k8s.io/v1
                        kind: ClusterRoleBinding
                        metadata:
                            name: dedicated-admin-serviceaccounts-c0
                        roleRef:
                            apiGroup: rbac.authorization.k8s.io
                            kind: ClusterRole
                            name: dedicated-admins-cluster
                        subjects:
                            - apiGroup: rbac.authorization.k8s.io
                              kind: Group
                              name: system:serviceaccounts:dedicated-admin
                pruneObjectBehavior: DeleteIfCreated
                remediationAction: enforce
                severity: low
        - objectDefinition:
            apiVersion: policy.open-cluster-management.io/v1
            kind: ConfigurationPolicy
            metadata:
                name: rbac-permissions-operator-config-sp2
            spec:
                evaluationInterval:
                    compliant: 2m
                    noncompliant: 45s
                namespaceSelector:
                    exclude:
                        - kube
                        - kube-*
                        - openshift
                        - openshift-*
                        - default
                        - redhat-*
                    include:
                        - '*'
                object-templates:
                    - complianceType: mustonlyhave
                      metadataComplianceType: musthave
                      objectDefinition:
                        apiVersion: rbac.authorization.k8s.io/v1
                        kind: RoleBinding
                        metadata:
                            name: dedicated-admin-serviceaccounts-0
                        roleRef:
                            apiGroup: rbac.authorization.k8s.io
                            kind: ClusterRole
                            name: dedicated-admins-project
                        subjects:
                            - apiGroup: rbac.authorization.k8s.io
                              kind: Group
                              name: system:serviceaccounts:dedicated-admin
                pruneObjectBehavior: DeleteIfCreated
                remediationAction: enforce
                severity: low
        - objectDefinition:
            apiVersion: policy.open-cluster-management.io/v1
            kind: ConfigurationPolicy
            metadata:
                name: rbac-permissions-operator-config-sp3
            spec:
                evaluationInterval:
                    compliant: 2m
                    noncompliant: 45s
                namespaceSelector:
                    exclude:
                        - kube
                        - kube-*
                        - openshift
                        - openshift-*
                        - default
                        - redhat-*
                    include:
                        - '*'
                object-templates:
                    - complianceType: mustonlyhave
                      metadataComplianceType: musthave
                      objectDefinition:
                        apiVersion: rbac.authorization.k8s.io/v1
                        kind: RoleBinding
                        metadata:
                            name: dedicated-admin-serviceaccounts-1
                        roleRef:
                            apiGroup: rbac.authorization.k8s.io
                            kind: ClusterRole
                            name: admin
                        subjects:
                            - apiGroup: rbac.authorization.k8s.io
                              kind: Group
                              name: system:serviceaccounts:dedicated-admin
                pruneObjectBehavior: DeleteIfCreated
                remediationAction: enforce
                severity: low
        - objectDefinition:
            apiVersion: policy.open-cluster-management.io/v1
            kind: ConfigurationPolicy
            metadata:
                name: rbac-permissions-operator-config-sp4
            spec:
                evaluationInterval:
                    compliant: 2m
                    noncompliant: 45s
                object-templates:
                    - complianceType: mustonlyhave
                      metadataComplianceType: musthave
                      objectDefinition:
                        apiVersion: rbac.authorization.k8s.io/v1
                        kind: ClusterRoleBinding
                        metadata:
                            name: dedicated-admins-c0
                        roleRef:
                            apiGroup: rbac.authorization.k8s.io
                            kind: ClusterRole
                            name: dedicated-admins-cluster
                        subjects:
                            - apiGroup: rbac.authorization.k8s.io
                              kind: Group
                              name: dedicated-admins
                pruneObjectBehavior: DeleteIfCreated
                remediationAction: enforce
                severity: low
        - objectDefinition:
            apiVersion: policy.open-cluster-management.io/v1
            kind: ConfigurationPolicy
            metadata:
                name: rbac-permissions-operator-config-sp5
            spec:
                evaluationInterval:
                    compliant: 2m
                    noncompliant: 45s
                namespaceSelector:
                    exclude:
                        - kube
                        - kube-*
                        - openshift
                        - openshift-*
                        - default
                        - redhat-*
                    include:
                        - '*'
                object-templates:
                    - complianceType: mustonlyhave
                      metadataComplianceType: musthave
                      objectDefinition:
                        apiVersion: rbac.authorization.k8s.io/v1
                        kind: RoleBinding
                        metadata:
                            name: dedicated-admins-0
                        roleRef:
                            apiGroup: rbac.authorization.k8s.io
                            kind: ClusterRole
                            name: dedicated-admins-project
                        subjects:
                            - apiGroup: rbac.authorization.k8s.io
                              kind: Group
                              name: dedicated-admins
                pruneObjectBehavior: DeleteIfCreated
                remediationAction: enforce
                severity: low
        - objectDefinition:
            apiVersion: policy.open-cluster-management.io/v1
            kind: ConfigurationPolicy
            metadata:
                name: rbac-permissions-operator-config-sp6
            spec:
                evaluationInterval:
                    compliant: 2m
                    noncompliant: 45s
                namespaceSelector:
                    exclude:
                        - kube
                        - kube-*
                        - openshift
                        - openshift-*
                        - default
                        - redhat-*
                    include:
                        - '*'
                object-templates:
                    - complianceType: mustonlyhave
                      metadataComplianceType: musthave
                      objectDefinition:
                        apiVersion: rbac.authorization.k8s.io/v1
                        kind: RoleBinding
                        metadata:
                            name: dedicated-admins-1
                        roleRef:
                            apiGroup: rbac.authorization.k8s.io
                            kind: ClusterRole
                            name: admin
                        subjects:
                            - apiGroup: rbac.authorization.k8s.io
                              kind: Group
                              name: dedicated-admins
                pruneObjectBehavior: DeleteIfCreated
                remediationAction: enforce
                severity: low
        - objectDefinition:
            apiVersion: policy.open-cluster-management.io/v1
            kind: ConfigurationPolicy
            metadata:
                name: rbac-permissions-operator-config-sp7
            spec:
                evaluationInterval:
                    compliant: 2m
                    noncompliant: 45s
                namespaceSelector:
                    include:
                        - openshift-operators
                        - openshift-operators-redhat
                object-templates:
                    - complianceType: mustonlyhave
                      metadataComplianceType: musthave
                      objectDefinition:
                        apiVersion: rbac.authorization.k8s.io/v1
                        kind: RoleBinding
                        metadata:
                            name: dedicated-admins-core-ns-0
                        roleRef:
                            apiGroup: rbac.authorization.k8s.io
                            kind: ClusterRole
                            name: dedicated-admins-project
                        subjects:
                            - apiGroup: rbac.authorization.k8s.io
                              kind: Group
                              name: dedicated-admins
                pruneObjectBehavior: DeleteIfCreated
                remediationAction: enforce
                severity: low
        - objectDefinition:
            apiVersion: policy.open-cluster-management.io/v1
            kind: ConfigurationPolicy
            metadata:
                name: rbac-permissions-operator-config-sp8
            spec:
                evaluationInterval:
                    compliant: 2m
                    noncompliant: 45s
                namespaceSelector:
                    include:
                        - openshift-operators
                        - openshift-operators-redhat
                object-templates:
                    - complianceType: mustonlyhave
                      metadataComplianceType: musthave
                      objectDefinition:
                        apiVersion: rbac.authorization.k8s.io/v1
                        kind: RoleBinding
                        metadata:
                            name: dedicated-admins-core-ns-1
                        roleRef:
                            apiGroup: rbac.authorization.k8s.io
                            kind: ClusterRole
                            name: admin
                        subjects:
                            - apiGroup: rbac.authorization.k8s.io
                              kind: Group
                              name: dedicated-admins
                pruneObjectBehavior: DeleteIfCreated
                remediationAction: enforce
                severity: low
        - objectDefinition:
            apiVersion: policy.open-cluster-management.io/v1
            kind: ConfigurationPolicy
            metadata:
                name: rbac-permissions-operator-config-sp9
            spec:
                evaluationInterval:
                    compliant: 2m
                    noncompliant: 45s
                namespaceSelector:
                    include:
                        - openshift-operators
                        - openshift-operators-redhat
                object-templates:
                    - complianceType: mustonlyhave
                      metadataComplianceType: musthave
                      objectDefinition:
                        apiVersion: rbac.authorization.k8s.io/v1
                        kind: RoleBinding
                        metadata:
                            name: dedicated-admin-serviceaccounts-core-ns-0
                        roleRef:
                            apiGroup: rbac.authorization.k8s.io
                            kind: ClusterRole
                            name: dedicated-admins-project
                        subjects:
                            - apiGroup: rbac.authorization.k8s.io
                              kind: Group
                              name: system:serviceaccounts:dedicated-admin
                pruneObjectBehavior: DeleteIfCreated
                remediationAction: enforce
                severity: low
        - objectDefinition:
            apiVersion: policy.open-cluster-management.io/v1
            kind: ConfigurationPolicy
            metadata:
                name: rbac-permissions-operator-config-sp10
            spec:
                evaluationInterval:
                    compliant: 2m
                    noncompliant: 45s
                namespaceSelector:
                    include:
                        - openshift-operators
                        - openshift-operators-redhat
                object-templates:
                    - complianceType: mustonlyhave
                      metadataComplianceType: musthave
                      objectDefinition:
                        apiVersion: rbac.authorization.k8s.io/v1
                        kind: RoleBinding
                        metadata:
                            name: dedicated-admin-serviceaccounts-core-ns-1
                        roleRef:
                            apiGroup: rbac.authorization.k8s.io
                            kind: ClusterRole
                            name: admin
                        subjects:
                            - apiGroup: rbac.authorization.k8s.io
                              kind: Group
                              name: system:serviceaccounts:dedicated-admin
                pruneObjectBehavior: DeleteIfCreated
                remediationAction: enforce
                severity: low
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
    name: placement-rbac-permissions-operator-config-sp
    namespace: openshift-acm-policies
spec:
    clusterSelector:
        matchExpressions:
            - key: hypershift.open-cluster-management.io/hosted-cluster
              operator: In
              values:
                - "true"
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
    name: binding-rbac-permissions-operator-config-sp
    namespace: openshift-acm-policies
placementRef:
    apiGroup: apps.open-cluster-management.io
    kind: PlacementRule
    name: placement-rbac-permissions-operator-config-sp
subjects:
    - apiGroup: policy.open-cluster-management.io
      kind: Policy
      name: rbac-permissions-operator-config-sp
