deploymentMode: "SelectorSyncSet"
selectorSyncSet:
  matchExpressions:
  - key: ext-hypershift.openshift.io/cluster-type
    operator: In
    values: ["service-cluster", "management-cluster-v2"]
  - key: api.openshift.com/fedramp
    operator: NotIn
    values: ["true"]
