apiVersion: operators.coreos.com/v1
applyMode: AlwaysApply
kind: OperatorSource
name: community-operators
namespace: openshift-marketplace
patch: |-
  { "spec": { "registryNamespace": "curated-community-operators" } }
patchType: merge