apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    monitoring.openshift.io/collection-profile: full
  name: ethtool-exporter
  namespace: openshift-sre-ethtool-exporter
spec:
  endpoints:
    - interval: 15s
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      port: https
      scheme: https
      tlsConfig:
        serverName: ethtool-exporter.openshift-sre-ethtool-exporter.svc
        ca:
          configMap:
            key: service-ca.crt
            name: openshift-service-ca.crt
        cert:
          secret:
            key: tls.crt
            name: ethtool-exporter-tls
        keySecret:
          key: tls.key
          name: ethtool-exporter-tls
      metricRelabelings:
        - action: keep
          regex: node_ethtool_.*_allowance_exceeded
          sourceLabels:
            - __name__
      relabelings:
        - action: replace
          regex: (.*)
          replacement: $1
          sourceLabels:
            - __meta_kubernetes_pod_node_name
          targetLabel: instance
  jobLabel: app.kubernetes.io/name
  namespaceSelector:
    matchNames:
      - openshift-sre-ethtool-exporter
  selector:
    matchLabels:
      app: ethtool-exporter
