apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: backplane-cssre-readers-impersonate
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: backplane-cssre-readers-cluster
subjects:
- kind: Group
  name: openshift-backplane-cssre
