apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: backplane-cssre
  namespace: openshift-monitoring
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:serviceaccounts:openshift-backplane-cssre
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: backplane-cssre
  namespace: openshift-monitoring
