deploymentMode: "SelectorSyncSet"
selectorSyncSet:
  matchLabels:
      api.openshift.com/addon-rhmi-operator: "true"
      api.openshift.com/addon-rhmi-operator-internal: "true"
      api.openshift.com/addon-managed-api-service: "true"
  matchLabelsApplyMode: "OR"
