apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: "scanning-operator"
  namespace: "openshift-scanning-operator"
spec:
  channel: ${CHANNEL}
  installPlanApproval: "Automatic"
  source: "scanning-operator-catalog"
  sourceNamespace: "openshift-scanning-operator"
  name: "scanning-operator"
