kind: Namespace
apiVersion: v1
name: open-cluster-management-agent-addon
applyMode: AlwaysApply
patch: |-
  { "metadata": {"labels": {"hypershift.openshift.io/monitoring":"true"} } }
patchType: merge
