apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    app.kubernetes.io/managed-by: osd-cluster-ready
    app.kubernetes.io/part-of: openshift-monitoring
  name: osd-cluster-ready
  namespace: openshift-monitoring
spec:
  egress:
  - {}
  podSelector:
    matchLabels:
      job-name: osd-cluster-ready
  policyTypes:
  - Ingress
  - Egress
