apiVersion: monitoring.openshift.io/v1alpha1
kind: RouteMonitor
metadata:
  name: console
  namespace: openshift-route-monitor-operator
spec:
  route:
    name: console
    namespace: openshift-console
  slo:
    targetAvailabilityPercent: "99.95"
