apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backplane-mtsre-addon-operator-admin
rules:
  - apiGroups:
    - "addons.managed.openshift.io"
    resources:
      - "addonoperators"
      - "addons"
    verbs:
      - get
      - list
      - watch
      - patch
      - update
