---
deploymentMode: "SelectorSyncSet"
selectorSyncSet:
  resourceApplyMode: Sync
  matchExpressions:
    - key: ext-hypershift.openshift.io/cluster-type
      operator: NotIn
      values: ["management-cluster", "service-cluster"]
    - key: api.openshift.com/fedramp
      operator: NotIn
      values: ["true"]
    - key: api.openshift.com/addon-managed-api-service-internal
      operator: NotIn
      values: ["true"]
    - key: api.openshift.com/addon-managed-api-service
      operator: NotIn
      values: ["true"]
