apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hypershift-addon-agent-crd-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: hypershift-addon-agent-crd-reader
subjects:
- kind: ServiceAccount
  name: hypershift-addon-agent-sa
  namespace: open-cluster-management-agent-addon
