apiVersion: v1
kind: ConfigMap
metadata:
  name: managed-upgrade-operator-config
  namespace: openshift-managed-upgrade-operator
data:
  config.yaml: |
    configManager:
      source: OCM
      ocmBaseUrl: ${OCM_BASE_URL}
      watchInterval: 60
    maintenance:
      controlPlaneTime: 90
      ignoredAlerts:
        controlPlaneCriticals:
        # ClusterOperatorDown - OSD-6330
        - ClusterOperatorDown
        # ClusterOperatorDegraded - OSD-6330
        - ClusterOperatorDegraded
    scale:
      timeOut: 30
    upgradeWindow:
      delayTrigger: 30
      timeOut: 120
    nodeDrain:
      timeOut: 45
      expectedNodeDrainTime: 8
    healthCheck:
      ignoredCriticals:
      - DNSErrors05MinSRE
      - MetricsClientSendFailingSRE
      - UpgradeNodeScalingFailedSRE
      - UpgradeClusterCheckFailedSRE
      - PrometheusRuleFailures
      - CannotRetrieveUpdates
      - FluentdNodeDown
      ignoredNamespaces:
      - openshift-logging
      - openshift-redhat-marketplace
      - openshift-operators
      - openshift-customer-monitoring
      - openshift-route-monitoring-operator
      - openshift-user-workload-monitoring
      - openshift-pipelines
    extDependencyAvailabilityChecks:
      http:
        timeout: 10
        urls:
          - ${OCM_BASE_URL}
