apiVersion: v1
kind: ConfigMap
metadata:
  name: managed-upgrade-operator-config
  namespace: openshift-managed-upgrade-operator
data:
  config.yaml: |
    ocmBaseUrl: "${{OCM_BASE_URL}}"
    maintenance:
      controlPlaneTime: 90
      workerNodeTime: 8
      ignoredAlerts:
        controlPlaneCriticals:
        - etcdMembersDown
        - KubeDeploymentReplicasMismatch
        - ClusterOperatorDown
        - MachineWithNoRunningPhase
        - ClusterOperatorDegraded
    scale:
      timeOut: 30
    upgradeWindow:
      timeOut: 60
    nodeDrain:
      timeOut: 45
    healthCheck:
      ignoredCriticals:
      - DNSErrors05MinSRE
      - MetricsClientSendFailingSRE
      - UpgradeNodeScalingFailedSRE
      - UpgradeClusterCheckFailedSRE
