apiVersion: v1
kind: ConfigMap
metadata:
  name: managed-upgrade-operator-config
  namespace: openshift-managed-upgrade-operator
data:
  config.yaml: |
    configManager:
      source: OCM
      ocmBaseUrl: ${OCM_BASE_URL}
      watchInterval: 60
    maintenance:
      controlPlaneTime: 120
      ignoredAlerts:
        controlPlaneCriticals:
        # ClusterOperatorDown - https://bugzilla.redhat.com/show_bug.cgi?id=1955300
        - ClusterOperatorDown
    scale:
      timeOut: 30
    upgradeWindow:
      delayTrigger: 30
      timeOut: 120
    nodeDrain:
      timeOut: 45
      expectedNodeDrainTime: 8
    healthCheck:
      ignoredCriticals:
      - DNSErrors05MinSRE
      - MetricsClientSendFailingSRE
      - UpgradeNodeScalingFailedSRE
      - UpgradeClusterCheckFailedSRE
      - PruningCronjobErrorSRE
      - PrometheusRuleFailures
      - CannotRetrieveUpdates
      - FluentdNodeDown
      # https://bugzilla.redhat.com/show_bug.cgi?id=1986981
      - PrometheusRemoteWriteBehind
      - KubePersistentVolumeErrors
      - PrometheusBadConfig
      - PrometheusRemoteStorageFailures
      - AlertmanagerMembersInconsistent
      - AlertmanagerClusterFailedToSendAlerts
      - AlertmanagerConfigInconsistent
      - AlertmanagerClusterDown
      - KubeStateMetricsListErrors
      - KubeStateMetricsWatchErrors
      - ThanosRuleSenderIsFailingAlerts
      - ThanosRuleHighRuleEvaluationFailures
      - ThanosNoRuleEvaluations
      ignoredNamespaces:
      - openshift-logging
      - openshift-redhat-marketplace
      - openshift-operators
      - openshift-customer-monitoring
      - openshift-cnv
      - openshift-route-monitoring-operator
      - openshift-user-workload-monitoring
      - openshift-pipelines
    extDependencyAvailabilityChecks:
      http:
        timeout: 10
        urls:
          - ${OCM_BASE_URL}
