apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: sre-cloud-ingress-operator-offline-alerts
    role: alert-rules
  name: sre-cloud-ingress-operator-offline-alerts
  namespace: openshift-monitoring
spec:
  groups:
  - name: sre-cloud-ingress-operator-offline-alerts
    rules:
    - alert: CloudIngressOperatorOfflineSRE
      expr: absent(up{service="localmetrics-cloud-ingress-operator", namespace="openshift-cloud-ingress-operator"})
      for: 15m
      labels:
        severity: critical
        namespace: openshift-monitoring