apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: "compliance-operator"
  namespace: "openshift-compliance"
spec:
  channel: "4.6"
  installPlanApproval: "Manual"
  source: "redhat-operators"
  sourceNamespace: "openshift-marketplace"
  name: "compliance-operator"
