---
kind: ClusterResourceQuota
apiVersion: quota.openshift.io/v1
metadata:
  name: persistent-volume-quota
spec:
  selector:
    annotations: null
    labels:
      matchExpressions:
      - key: storage_pv_quota
        operator: DoesNotExist
  quota:
    hard:
      requests.storage: 100
---
kind: ClusterResourceQuota
apiVersion: quota.openshift.io/v1
metadata:
  name: loadbalancer-quota
spec:
  selector:
    annotations: null
    labels:
      matchExpressions:
      - key: service_lb_quota
        operator: DoesNotExist
  quota:
    hard:
      services.loadbalancers: 2
