deploymentMode: SelectorSyncSet
selectorSyncSet:
  matchExpressions:
  - key: hive.openshift.io/version-major-minor
    operator: In
    values: ["4.17", "4.18"]
  - key: api.openshift.com/gate-wif
    operator: In
    values: ["4.19"]
  - key: api.openshift.com/wif
    operator: In
    values: ["true"]
