apiVersion: managed.openshift.io/v1alpha1
kind: SubjectPermission
metadata:
  name: backplane-cssre-rhoc-admins-project
  namespace: openshift-rbac-permissions
spec:
  permissions:
  - allowFirst: true
    clusterRoleName: backplane-cssre-rhoc-admins-project
    namespacesAllowedRegex: (^redhat-openshift-connectors$)
  subjectKind: Group
  subjectName: system:serviceaccounts:openshift-backplane-cssre
