apiVersion: managed.openshift.io/v1alpha1
kind: SubjectPermission
metadata:
  name: backplane-mtsre-openshift-connectors
  namespace: openshift-rbac-permissions
spec:
  permissions:
  - clusterRoleName: admin
    namespacesAllowedRegex: (^redhat-openshift-connectors$)
    namespacesDeniedRegex: openshift-backplane-cluster-admin
  - clusterRoleName: backplane-openshift-connectors-cr-project
    namespacesAllowedRegex: (^redhat-openshift-connectors$)
    namespacesDeniedRegex: openshift-backplane-cluster-admin
  - clusterRoleName: backplane-mtsre-monitoring-project
    namespacesAllowedRegex: (^redhat-openshift-connectors$)
    namespacesDeniedRegex: openshift-backplane-cluster-admin
  subjectKind: Group
  subjectName: system:serviceaccounts:openshift-backplane-mtsre
