apiVersion: operator.openshift.io/v1
kind: CloudCredential
name: cluster
applyMode: AlwaysApply
patch: '{"metadata":{"annotations":{"cloudcredential.openshift.io/upgradeable-to":"v4.9"}}}'
patchType: merge
