deploymentMode: "SelectorSyncSet"
selectorSyncSet:
  matchExpressions:
  - key: hive.openshift.io/version-major-minor
    operator: In
    values: ["4.8"]
  - key: api.openshift.com/channel-group
    operator: In
    values: ["fast"]
