apiVersion: managed.openshift.io/v1alpha1
kind: SubjectPermission
metadata:
  name: backplane-rhmi-cssre-admins
  namespace: openshift-rbac-permissions
spec:
  permissions:
  - allowFirst: true
    clusterRoleName: backplane-rhmi-cssre-admins-project
    namespacesAllowedRegex: ^redhat-.*$
    namespacesDeniedRegex: (^kube$|^kube-.*|^openshift$|^openshift-.*|^default$)
  subjectKind: Group
  subjectName: system:serviceaccounts:openshift-backplane-cssre
