apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: "windows-vcpu-overcommit-binding"
spec:
  policyName: "windows-vcpu-overcommit"
  validationActions: [Deny]

