apiVersion: machineconfiguration.openshift.io/v1
kind: KubeletConfig
metadata:
  name: custom-kubelet
spec:
  machineConfigPoolSelector:
    matchLabels:
      managed.openshift.io/custom-kubelet: true
  kubeletConfig:
    systemReserved:
      cpu: 1000m
      memory: 1Gi
