---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: osd-delete-prometheus-operator-bz1891815
  namespace: openshift-monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: osd-delete-prometheus-operator-bz1891815
  namespace: openshift-monitoring
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - delete
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: osd-delete-prometheus-operator-bz1891815
  namespace: openshift-monitoring
subjects:
- kind: ServiceAccount
  name: osd-delete-prometheus-operator-bz1891815
  namespace: openshift-monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: osd-delete-prometheus-operator-bz1891815
  namespace: openshift-monitoring
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: osd-delete-prometheus-operator-bz1891815
  namespace: openshift-monitoring
spec:
  failedJobsHistoryLimit: 3
  successfulJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  schedule: "*/30 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: osd-delete-prometheus-operator-bz1891815
          restartPolicy: Never
          containers:
          - name: osd-delete-prometheus-operator-bz1891815
            image: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest
            imagePullPolicy: Always
            args:
            - /bin/bash
            - -c
            - |
              POD=$(oc -n openshift-monitoring get pods -l app.kubernetes.io/name=prometheus-operator -o name)
              oc -n openshift-monitoring delete $POD