deploymentMode: SelectorSyncSet
selectorSyncSet:
  matchExpressions:
  - key: hive.openshift.io/version-major-minor
    operator: In
    values: ["4.20"]
  - key: api.openshift.com/wif
    operator: In
    values: ["true"]
