deploymentMode: "SelectorSyncSet"
selectorSyncSet:
  matchExpressions:
    - key: hive.openshift.io/version-major-minor
      operator: NotIn
      values: ["4.5"]
    - key: ext-managed.openshift.io/uwm-disabled
      operator: NotIn
      values: ["true"]
    - key: ext-managed.openshift.io/fedramp
      operator: NotIn
      values: ["true"]
