apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: sre-dns-alerts
    role: alert-rules
  name: sre-dns-alerts
spec:
  groups:
  - name: sre-dns-alerts
    rules:
    - alert: DNSLatencyOver200ms5MinSREO
      expr: max_over_time(dns_latency_milliseconds_sum[5m]) > 0.2
      labels:
        severity: critical
    - alert: DNSErrors05MinSREO
      expr: rate(dns_failure_failure_total[5m]) > 0
      labels:
        severity: critical