apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: 5min-object-backup
  namespace: openshift-velero
spec:
  schedule: '*/5 * * * *'
  template:
    includedNamespaces:
    - '*'
    snapshotVolumes: false
    ttl: 0h25m0s
