apiVersion: imageregistry.operator.openshift.io/v1
applyMode: AlwaysApply
kind: Config
name: cluster
# patch registry to expose default route: https://docs.openshift.com/container-platform/4.1/registry/configuring-registry-operator.html#registry-operator-default-crd_configuring-registry-operator
patch: '{"spec":{"defaultRoute":true}}'
patchType: merge
