apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  name: managed-velero-operator-iam-credentials
  namespace: openshift-velero
spec:
  secretRef:
    name: managed-velero-operator-iam-credentials
    namespace: openshift-velero
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: AWSProviderSpec
    statementEntries:
    - effect: Allow
      action:
      - s3:CreateBucket
      - s3:ListBucket
      - s3:PutBucketAcl
      - s3:PutBucketPublicAccessBlock
      - s3:PutEncryptionConfiguration
      - s3:PutLifecycleConfiguration
      resource: "*"
