deploymentMode: SelectorSyncSet
selectorSyncSet:
  matchExpressions:
  - key: api.openshift.com/sts
    operator: NotIn
    values: ["true"]
  - key: api.openshift.com/private-link
    operator: NotIn
    values: ["true"]
  - key: api.openshift.com/fedramp
    operator: NotIn
    values: ["true"]
