deploymentMode: SelectorSyncSet
selectorSyncSet:
  matchExpressions:
    - key: api.openshift.com/fedramp
      operator: In
      values:
        - "true"
    - key: api.openshift.com/environment
      operator: NotIn
      values:
        - "production" 
