deploymentMode: "SelectorSyncSet"
selectorSyncSet:
  resourceApplyMode: Sync
  matchExpressions:
  - key: api.openshift.com/environment
    operator: In
    values: ["staging", "integration"]
  - key: hive.openshift.io/version-major-minor
    operator: In
    values: ["4.8","4.9","4.10"]
