deploymentMode: SelectorSyncSet
selectorSyncSet: 
  applyBehavior: "CreateOnly"
  matchExpressions: 
    - key: api.openshift.com/ccs
      operator: In
      values: ["true"]
    - key: hive.openshift.io/cluster-platform
      operator: In
      values: ["gcp"]
   
