deploymentMode: "SelectorSyncSet"
selectorSyncSet:
  matchExpressions:
  - key: api.openshift.com/fedramp
    operator: In
    values:
      - "true"
  - key: hive.openshift.io/cluster-region
    operator: In
    values:
      - "us-gov-west-1"
  - key: api.openshift.com/sts
    operator: In
    values:
      - "true"
  - key: api.openshift.com/private-link
    operator: In
    values:
      - "true"
