deploymentMode: SelectorSyncSet
selectorSyncSet:
  matchExpressions:
    - key: api.openshift.com/fedramp
      operator: In
      values:
        - "true"
    - key: api.openshift.com/environment
      operator: In
      values:
        - "production"
    - key: hive.openshift.io/version-major-minor
      operator: In
      values: ["4.11", "4.12"]
