apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backplane-cee-readers-cluster
rules:
# CEE can view machineconfigs, machineconfigpools, kubeletconfigs,controllerconfigs
- apiGroups:
  - machineconfiguration.openshift.io
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
# CEE can view machines, machinehealthchecks, machinesets
- apiGroups:
  - machine.openshift.io
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
# CEE can view api request counts
- apiGroups:
  - apiserver.openshift.io
  resources:
  - apirequestcounts
  verbs:
  - get
  - list
  - watch
# CEE can view Addon, AddonInstance, AddonOperator
- apiGroups:
  - addons.managed.openshift.io
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
