apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: backplane-cee-mustgather
  namespace: openshift-must-gather-operator
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:serviceaccounts:openshift-backplane-cee
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: backplane-cee-mustgather
  namespace: openshift-must-gather-operator