apiVersion: v1
kind: ServiceAccount
metadata:
  name: icsp-pruner-sa
  namespace: openshift-sre-pruning
  annotations:
    managed.openshift.io/source: ITN-2025-00316
    managed.openshift.io/description: "CronJob ServiceAccount to prune ImageContentSourcePolicy 'image-policy'"
