apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: icsp-pruner-crb
  annotations:
    managed.openshift.io/source: ITN-2025-00316
    managed.openshift.io/description: "CronJob ClusterRoleBinding to prune ImageContentSourcePolicy 'image-policy'"
roleRef:
  kind: ClusterRole
  name: icsp-pruner-cr
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: icsp-pruner-sa
  namespace: openshift-sre-pruning
