apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: sre-rbac-permissions-operator-offline-alerts
    role: alert-rules
  name: sre-rbac-permissions-operator-offline-alerts
  namespace: openshift-monitoring
spec:
  groups:
  - name: sre-rbac-permissions-operator-offline-alerts
    rules:
    - alert: RbacPermissionsOperatorOfflineSRE
      expr: absent(up{service="rbac-permissions-operator"})
      for: 15m
      labels:
        severity: critical
        namespace: openshift-monitoring
