apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: sre-kubequotaexceeded
    role: alert-rules
  name: sre-kubequotaexceeded
  namespace: openshift-monitoring
spec:
  groups:
  - name: sre-kubequotaexceeded
    rules:
    - alert: KubeQuotaExceededSRE
      expr: |
        kube_resourcequota{namespace=~"(openshift-.*|kube-.*|default|logging)",job="kube-state-metrics", type="used"}
        / ignoring(instance, job, type)
        (kube_resourcequota{namespace=~"(openshift-.*|kube-.*|default|logging)",job="kube-state-metrics", type="hard"} > 0)
        > 1
      for: 30m
      labels:
        severity: critical
        namespace: openshift-monitoring
      annotations:
        message: Quota limit exceeded in namespace {{ $labels.namespace }}.

