apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: sre-ebs-iops-burstbalance
    role: alert-rules
    api.openshift.com/managed: "true"
    hive.openshift.io/cluster-platform: "aws"
  name: sre-ebs-iops-burstbalance
  namespace: openshift-monitoring
spec:
  groups:
  - name: sre-ebs-iops-burstbalance
    rules:
    - alert: EbsVolumeBurstBalanceLT40PctSRE
      expr: avg(ebs_iops_credits) < 40
      for: 60m
      labels:
        severity: warning
        namespace: openshift-monitoring
    - alert: EbsVolumeBurstBalanceLT20PctSRE
      expr: avg(ebs_iops_credits) < 20
      for: 60m
      labels:
        severity: critical
        namespace: openshift-monitoring