apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: sre-cluster-operator-down-alerts
    role: alert-rules
  name: sre-cluster-operator-down-alerts
  namespace: openshift-monitoring
spec:
  groups:
  - name: sre-cluster-operator-down-alerts
    rules:
    - alert: ClusterOperatorOfflineSRE
      expr: cluster_operator_up == 0
      for: 15m
      labels:
        severity: critical
    - alert: ClusterOperatorDegradedSRE
      expr: cluster_operator_conditions{condition='Degraded'} == 1
      for: 15m
      labels:
        severity: critical
