apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: sre-alerts-stuck-builds
    role: alert-rules
    api.openshift.com/managed: "true"
  name: sre-alerts-stuck-builds
  namespace: openshift-monitoring
spec:
  groups:
  - name: sre-alerts-stuck-builds
    rules:
    - alert: StuckNewBuilds3MinSRE
      expr: count(openshift_build_active_time_seconds{phase="New"} < time() - 180) > 0
      labels:
        severity: warning
        namespace: openshift-monitoring