apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: sre-filesysfull
    role: alert-rules
    api.openshift.com/managed: "true"
  name: sre-filesysfull
  namespace: openshift-monitoring
spec:
  groups:
  - name: sre-filesysfull
    rules:
      # This matches with the default KubePersistentVolumeUsageCritical; this rule inverts the regex match.
    - alert: KubeCustomerPersistentVolumeUsageCriticalSRE
      expr: |
        100
        * kubelet_volume_stats_available_bytes{job="kubelet",namespace!~"(openshift-.*|kube-.*|default|logging)"}
        / kubelet_volume_stats_capacity_bytes{job="kubelet",namespace!~"(openshift-.*|kube-.*|default|logging)"}
        < 3
      labels:
        severity: warning
        namespace: openshift-monitoring
      annotations:
        message: "The customer PersistentVolume claimed by {{ $labels.persistentvolumeclaim }} in Namespace {{ $labels.namespace }} is only {{ printf \"%0.2f\" $value }}% free."
        link: "https://github.com/openshift/ops-sop/blob/master/v4/alerts/KubeCustomerPersistentVolumeUsageCritical.md"

      # This matches with the default KubePersistentVolumeFullInFourDays; this rule inverts the regex match.
    - alert: KubeCustomerPersistentVolumeFullInFourDaysSRE
      expr: |
        100
        * (kubelet_volume_stats_available_bytes{job="kubelet",namespace!~"(openshift-.*|kube-.*|default|logging)"}
        / kubelet_volume_stats_capacity_bytes{job="kubelet",namespace!~"(openshift-.*|kube-.*|default|logging)"})
        < 15 and predict_linear(kubelet_volume_stats_available_bytes{job="kubelet",namespace!~"(openshift-.*|kube-.*|default|logging)"}[6h],
        4 * 24 * 3600) < 0
      labels:
        severity: warning
        namespace: openshift-monitoring
      annotations:
        message: "Based on recent sampling, the customer PersistentVolume claimed by {{ $labels.persistentvolumeclaim }} in Namespace {{ $labels.namespace }} is expected to fill up within four days. Currently {{ printf \"%0.2f\" $value }}% is available."
        link: "https://github.com/openshift/ops-sop/blob/master/v4/alerts/KubeCustomerPersistentVolumeUsageCritical.md"
