apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: aws-efs-alerts
    role: alert-rules
  name: aws-efs-alerts
  namespace: openshift-monitoring
spec:
  groups:
  - name: aws-efs-alerts 
    rules:
    - alert: MultipleVersionsOfEFSCSIDriverInstalled 
      expr: count(kube_pod_info{namespace="openshift-operators", pod=~"efs-csi-node-.*"}) > 0 and count(kube_pod_info{namespace="openshift-cluster-csi-drivers", pod=~"aws-efs-csi-driver-operator-.*"}) > 0
      labels:
        severity: critical
        namespace: openshift-monitoring
        source: "https://issues.redhat.com/browse/OSD-16223"
        link: "https://github.com/openshift/ops-sop/blob/master/v4/alerts/MultipleVersionsOfEFSCSIDriverInstalled.md"
      annotations:
        message: Multiple versions of EFS CSI Driver installed 
