---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: sre-cluster-version-operator
    role: alert-rules
  name: sre-cluster-version-operator
  namespace: openshift-monitoring
spec:
  groups:
    - name: sre-cluster-version-operator
      rules:
        - alert: ClusterOperatorDegradedSRE
          annotations:
            summary: Cluster operator has been degraded for 2 days.
            description: The {{ $labels.name }} operator is degraded because {{
              $labels.reason }}, and the components it manages may have reduced
              quality of service. Cluster upgrades may not complete. For more
              information refer to 'oc get -o yaml clusteroperator {{
              $labels.name }}' {{ with $console_url := "console_url" | query }}
              {{ if ne (len (label "url" (first $console_url))) 0 }} or {{ label
              "url" (first $console_url) }}/settings/cluster/{{ end }} {{ end
              }}.
          expr: >
            max by (namespace, name, reason)

            (
             (
               cluster_operator_conditions{job="cluster-version-operator", name!="version", condition="Degraded"}
               or on (namespace, name)
               cluster_operator_conditions{job="cluster-version-operator", name="version", condition="Failing"}
               or on (namespace, name)
               group by (namespace, name) (cluster_operator_up{job="cluster-version-operator"})
             ) == 1
            )
          for: 2d
          labels:
            link: https://github.com/openshift/ops-sop/blob/master/v4/alerts/ClusterOperatorDegraded.md
            namespace: openshift-monitoring
            severity: critical
