apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: sre-machine-api-node-mismatch
    role: alert-rules
  name: sre-machine-api-node-mismatch
  namespace: openshift-machine-api
spec:
  groups:
  - name: sre-machine-api-node-mismatch
    rules:
    - alert: NoNodeObjectForMachineWarningSRE
      expr: &promql machine_api_status == 0
      for: 15m
      severity: warning
      annotations:
        message: "The Machine object {{ $labels.machine_name }} hasn't had an associated Node for the past 30 minutes."
        link: &kcslink "https://access.redhat.com"
    - alert: NoNodeObjectForMachineCriticalSRE
      expr: *promql
      for: 30m
      severity: critical
      annotations:
        message: "The Machine object {{ $labels.machine_name }} hasn't had an associated Node for the past 60 minutes."
        link: *kcslink
