aggregationRule:
  clusterRoleSelectors:
  # aggregate all "cluster" scope rbac for CSSRE (includes dedicated-admins)
  - matchExpressions:
    - key: managed.openshift.io/aggregate-to-layered-cs-sre-admins
      operator: In
      values:
        - "cluster"
  - matchExpressions:
    - key: managed.openshift.io/aggregate-to-dedicated-admins
      operator: In
      values:
        - "cluster"
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: layered-cs-sre-admin-cluster
rules: []
