apiVersion: user.openshift.io/v1
kind: Group
metadata:
  name: layered-cs-sre-admins
users: # CS SRE team list
- ${RHMI_SRE_USER1}
- ${RHMI_SRE_USER2}
- ${RHMI_SRE_USER3}
- ${RHMI_SRE_USER4}
- ${RHMI_SRE_USER5}
- ${RHMI_SRE_USER6}
- ${RHMI_SRE_USER7}
- ${RHMI_SRE_USER8}