apiVersion: managed.openshift.io/v1alpha1
kind: SubjectPermission
metadata:
  name: layered-cs-sre-admin
  namespace: openshift-rbac-permissions
spec:
  clusterPermissions:
  - dedicated-admins-cluster
  - layered-cs-sre-admin-cluster
  permissions:
  - allowFirst: true
    clusterRoleName: layered-cs-sre-admin-project
    namespacesAllowedRegex: .*
    namespacesDeniedRegex: (^kube$|^kube-.*|^openshift$|^openshift-.*|^default$)
  subjectKind: Group
  subjectName: layered-cs-sre-admins  