deploymentMode: "SelectorSyncSet"
selectorSyncSet:
  matchExpressions:
    - key: ext-hypershift.openshift.io/cluster-type
      operator: NotIn
      values: ["management-cluster"]
    - key: hive.openshift.io/version-major-minor
      operator: NotIn
      values: ["4.5"]
    - key: ext-managed.openshift.io/uwm-disabled
      operator: NotIn
      values: ["true"]
