apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backplane-rhmi-lpsre-cluster-aggregate
  labels:
    managed.openshift.io/aggregate-to-lpsre-admins: "cluster"
rules:
# LP SRE can get infrastructure details (cluster)
- apiGroups:
  - config.openshift.io
  resources:
  - infrastructures
  - oauths
  verbs:
  - 'get'
# LP SRE can interact with RHMI ClusterResourceQuotas (Only for LA)
- apiGroups:
  - quota.openshift.io
  resources:
  - clusterresourcequotas/status
  - clusterresourcequotas
  verbs:
  - '*'
# LP SRE manage the following list of apigroups
- apiGroups:
  - "apiextensions.k8s.io"
  - "admin-enmasse.io"
  - "apicur.io"
  - "applicationmonitoring.integreatly.org"
  - "apps.3scale.net"
  - "capabilities.3scale.net"
  - "enmasse.io"
  - "iot.enmasse.io"
  - "keycloak.org"
  - "monitoring.coreos.com"
  - "push.aerogear.org"
  - "org.eclipse.che"
  - "syndesis.io"
  resources:
  - '*'
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
