apiVersion: managed.openshift.io/v1alpha1
kind: SubjectPermission
metadata:
  name: backplane-lpsre-service-cluster
  namespace: openshift-rbac-permissions
spec:
  clusterPermissions:
  - backplane-lpsre-service-cluster-cluster
  # permit get at global scope https://issues.redhat.com/browse/OSD-15997
  - view
  permissions:
  - clusterRoleName: backplane-lpsre-service-cluster-project
    namespacesAllowedRegex: "(^uhc.*|^ocm.*|^klusterlet.*)"
    namespacesDeniedRegex: openshift-backplane-cluster-admin
  - clusterRoleName: dedicated-readers
    namespacesAllowedRegex: "(^hypershift.*|^uhc.*|^ocm.*|^klusterlet.*|^open-cluster-management.*)"
    namespacesDeniedRegex: openshift-backplane-cluster-admin
  subjectKind: Group
  subjectName: system:serviceaccounts:openshift-backplane-lpsre
