deploymentMode: "SelectorSyncSet" 
selectorSyncSet: 
  resourceApplyMode: "Sync"
  matchExpressions:
  - key: hive.openshift.io/version-major-minor
    operator: In
    values: ["4.17"]
  - key: hive.openshift.io/cluster-platform
    operator: In
    values: ["gcp"]
