apiVersion: v1
kind: ServiceAccount
metadata:
  name: sre-pruner-sa
  namespace: openshift-sre-pruning
  labels:
    api.openshift.com/managed: "true"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sre-pruner-images
  labels:
    api.openshift.com/managed: "true"
roleRef:
  kind: ClusterRole
  name: system:image-pruner
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: sre-pruner-sa
  namespace: openshift-sre-pruning
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sre-pruner-buildsdeploys-cr
  labels:
    api.openshift.com/managed: "true"
rules:
# deployment pruning
- apiGroups:
  - ""
  resources:
  - pods
  - replicationcontrollers
  verbs:
  - list
  - get
- apiGroups:
  - ""
  resources:
  - replicationcontrollers
  verbs:
  - delete
- apiGroups:
  - apps.openshift.io
  resources:
  - deploymentconfigs
  verbs:
  - get
  - list
# builds pruning
- apiGroups:
  - build.openshift.io
  resources:
  - buildconfigs
  - builds
  verbs:
  - list
  - get
- apiGroups:
  - build.openshift.io
  resources:
  - builds
  verbs:
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sre-pruner-buildsdeploys-pruning
  labels:
    api.openshift.com/managed: "true"
roleRef: 
  kind: ClusterRole
  name: sre-pruner-buildsdeploys-cr
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: sre-pruner-sa
  namespace: openshift-sre-pruning
