apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backplane-srep-hive-project
rules:
# SRE can patch clusterdeployments (usually pause syncset)
- apiGroups:
  - hive.openshift.io
  resources:
  - clusterdeployments
  verbs:
  - patch
  - list # SRE can view clustersyncfailures via osdctl (SREP-2143)
# SRE can force re-sync a cluster
- apiGroups:
  - hiveinternal.openshift.io
  resources:
  - clustersyncs
  verbs:
  - delete
  - list # SRE can view clustersyncfailures via osdctl (SREP-2143)
