apiVersion: managed.openshift.io/v1alpha1
kind: SubjectPermission
metadata:
  name: backplane-srep-hive
  namespace: openshift-rbac-permissions
spec:
  permissions:
  - allowFirst: true
    clusterRoleName: backplane-srep-hive-project
    namespacesAllowedRegex: "(^uhc-.*)"
  - allowFirst: true
    clusterRoleName: backplane-srep-hive-osd-operators-reader
    namespacesAllowedRegex: "^.*-operator$"
    namespacesDeniedRegex: "^uhc-.*"
  subjectKind: Group
  subjectName: openshift-backplane-srep
