---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ohss-50230-redhat-operators-recovery
  namespace: openshift-marketplace
rules:
- apiGroups: [""]
  resources: [pods]
  verbs: [get, list, delete]
