---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ohss-50230-redhat-operators-recovery
  namespace: openshift-marketplace
subjects:
- kind: ServiceAccount
  name: ohss-50230-redhat-operators-recovery
  namespace: openshift-marketplace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ohss-50230-redhat-operators-recovery
