deploymentMode: "SelectorSyncSet"
selectorSyncSet:
  matchExpressions:
  # Target 4.16 clusters (primary impact from incident)
  - key: hive.openshift.io/version-major-minor
    operator: In
    values: ["4.16"]
  resourceApplyMode: "Sync"
