---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: osd-rebalance-infra-nodes-openshift-monitoring
  namespace: openshift-monitoring
subjects:
- kind: ServiceAccount
  name: osd-rebalance-infra-nodes
  namespace: openshift-monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: osd-rebalance-infra-nodes-openshift-monitoring
  namespace: openshift-monitoring