apiVersion: v1
kind: ConfigMap
metadata:
  name: managed-namespaces
  namespace: openshift-monitoring
data:
  managed_namespaces.yaml: |
    Resources:
      Namespace:
      - name: dedicated-admin
      - name: openshift-addon-operator
      - name: openshift-aqua
      - name: openshift-aws-vpce-operator
      - name: openshift-backplane
      - name: openshift-backplane-cee
      - name: openshift-backplane-csa
      - name: openshift-backplane-cse
      - name: openshift-backplane-csm
      - name: openshift-backplane-managed-scripts
      - name: openshift-backplane-mobb
      - name: openshift-backplane-srep
      - name: openshift-backplane-tam
      - name: openshift-cloud-ingress-operator
      - name: openshift-codeready-workspaces
      - name: openshift-compliance
      - name: openshift-container-security
      - name: openshift-custom-domains-operator
      - name: openshift-customer-monitoring
      - name: openshift-deployment-validation-operator
      - name: openshift-managed-node-metadata-operator      
      - name: openshift-file-integrity
      - name: openshift-logging
      - name: openshift-managed-upgrade-operator
      - name: openshift-must-gather-operator
      - name: openshift-observability-operator
      - name: openshift-ocm-agent-operator
      - name: openshift-operators-redhat
      - name: openshift-osd-metrics
      - name: openshift-rbac-permissions
      - name: openshift-route-monitor-operator
      - name: openshift-scanning
      - name: openshift-security
      - name: openshift-splunk-forwarder-operator
      - name: openshift-sre-pruning
      - name: openshift-strimzi
      - name: openshift-suricata
      - name: openshift-validation-webhook
      - name: openshift-velero
      - name: openshift-monitoring
      - name: openshift
      - name: openshift-cluster-version
