apiVersion: operators.coreos.com/v1
kind: CatalogSourceConfig
metadata:
  name: installed-redhat-openshift-logging
  namespace: openshift-marketplace
spec:
  csDisplayName: Red Hat Operators
  csPublisher: Red Hat
  packages: cluster-logging
  targetNamespace: openshift-logging
