apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: sre-machine-out-of-compliance
    role: alert-rules
  name: sre-machine-out-of-compliance
  namespace: openshift-monitoring
spec:
  groups:
  - name: sre-machine-out-of-compliance
    rules:
    - alert: MachineOutOfComplianceSRE
      # https://issues.redhat.com/browse/OSD-17905
      # This alert is a fallback in case the workload in https://issues.redhat.com/browse/OSD-17902 doesn't do it's job.
      expr: |
        mapi_machine_created_timestamp_seconds > 2419200
      for: 60m
      labels:
        severity: warning
        node: "{{ $labels.node }}"
        source: "https://issues.redhat.com/browse/OSD-17905"
        link: "https://github.com/openshift/ops-sop/blob/master/v4/alerts/hypershift/MachineOutOfCompliance.md"
      annotations:
        message:  A machine on a management cluster is older than 28 days.
