deploymentMode: "SelectorSyncSet"
selectorSyncSet:
  matchExpressions:
  - key: ext-hypershift.openshift.io/cluster-type
    operator: In
    values: ["management-cluster"]
  - key: api.openshift.com/fedramp
    operator: NotIn
    values: ["true"]
  - key: api.openshift.com/sts
    operator: In
    values: ["true"]
  - key: ext-hypershift.openshift.io/cluster-sector
    operator: NotIn
    values: ["ibm-infra"]
