apiVersion: hive.openshift.io/v1
kind: SelectorSyncSet
metadata:
  labels:
    managed.openshift.io/gitHash: ${IMAGE_TAG}
    managed.openshift.io/gitRepoName: ${REPO_NAME}
    managed.openshift.io/osd: 'true'
  name: osd-logging
spec:
  clusterDeploymentSelector:
    matchLabels:
      api.openshift.com/managed: 'true'
    matchExpressions:
    - key: ext-managed.openshift.io/extended-logging-support
      operator: In
      values:
      - 'true'
  resourceApplyMode: Upsert
  resources:
  - apiVersion: v1
    kind: Namespace
    metadata:
      name: openshift-logging
      annotations:
        openshift.io/node-selector: ''
      labels:
        managed.openshift.io/service-lb-quota-exempt: 'true'
        managed.openshift.io/storage-pv-quota-exempt: 'true'
        openshift.io/cluster-logging: 'true'
        openshift.io/cluster-monitoring: 'true'
  - apiVersion: operators.coreos.com/v1
    kind: OperatorGroup
    metadata:
      annotations:
        olm.providedAPIs: ClusterLogging.v1.logging.openshift.io
      name: openshift-logging
      namespace: openshift-logging
    spec:
      serviceAccount:
        metadata:
          creationTimestamp: null
      targetNamespaces:
      - openshift-logging
  - apiVersion: v1
    data:
      actions.yaml: '# ---

        # Remember, leave a key empty if there is no value.  None will be a string,

        # not a Python "NoneType"

        #

        # Also remember that all examples have ''disable_action'' set to True.  If
        you

        # want to use this action as a template, be sure to set this to False after

        # copying it.

        # actions:

        #   1:

        #     action: delete_indices

        #     description: >-

        #       Delete .operations indices older than 30 days.

        #       Ignore the error if the filter does not

        #       result in an actionable list of indices (ignore_empty_list).

        #       See https://www.elastic.co/guide/en/elasticsearch/client/curator/5.2/ex_delete_indices.html

        #     options:

        #       # Swallow curator.exception.NoIndices exception

        #       ignore_empty_list: True

        #       # In seconds, default is 300

        #       timeout_override: ${CURATOR_TIMEOUT}

        #       # Don''t swallow any other exceptions

        #       continue_if_exception: False

        #       # Optionally disable action, useful for debugging

        #       disable_action: False

        #     # All filters are bound by logical AND

        #     filters:

        #     - filtertype: pattern

        #       kind: regex

        #       value: ''^\.operations\..*$''

        #       exclude: False

        #     - filtertype: age

        #       # Parse timestamp from index name

        #       source: name

        #       direction: older

        #       timestring: ''%Y.%m.%d''

        #       unit: days

        #       unit_count: 30

        #       exclude: False

        '
      config.yaml: "# Logging example curator config file\n\n# uncomment and use this\
        \ to override the defaults from env vars\n#.defaults:\n#  delete:\n#    days:\
        \ 30\n.defaults:\n  delete:\n    days: 7\n\n# to keep ops logs for a different\
        \ duration:\n.operations:\n  delete:\n    days: 0\n\n# example for a normal\
        \ project\n#myapp:\n#  delete:\n#    weeks: 1\n"
      curator5.yaml: "---\nclient:\n  hosts:\n  - ${ES_HOST}\n  port: ${ES_PORT}\n\
        \  use_ssl: True\n  certificate: ${ES_CA}\n  client_cert: ${ES_CLIENT_CERT}\n\
        \  client_key: ${ES_CLIENT_KEY}\n  ssl_no_validate: False\n  timeout: ${CURATOR_TIMEOUT}\n\
        \  master_only: False\nlogging:\n  loglevel: ${CURATOR_LOG_LEVEL}\n  logformat:\
        \ default\n  blacklist: ['elasticsearch', 'urllib3']\n  \n"
    kind: ConfigMap
    metadata:
      name: curator
      namespace: openshift-logging
