deploymentMode: "SelectorSyncSet"
selectorSyncSet:
  matchExpressions:
  - key: api.openshift.com/fedramp
    operator: In
    values:
      - "true"
  - key: hive.openshift.io/cluster-region
    operator: In
    values:
      - "us-gov-east-1"
