apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backplane-ocs-provider-cr-project
rules:
  - apiGroups:
      - "odf.openshift.io"
    resources:
      - "storagesystems"
    verbs:
      - get
      - list
      - watch
      - patch
      - update
  - apiGroups:
      - "ocs.openshift.io"
    resources:
      - "storageclassclaims"
      - "storageconsumers"
      - "storageclusters"
      - "ocsinitializations"
      - "managedocs"
      - "managedocs/finalizers"
      - "managedocs/status"
    verbs:
      - get
      - list
      - watch
      - patch
      - update
  - apiGroups:
      - "noobaa.io"
    resources:
      - "noobaaaccounts"
    verbs:
      - get
      - list
      - watch
      - patch
      - update
  - apiGroups:
      - "ceph.rook.io"
    resources:
      - "cephbucketnotifications"
      - "cephbuckettopics"
      - "cephfilesystemsubvolumegroups"
    verbs:
      - get
      - list
      - watch
      - patch
      - update
  - apiGroups:
      - "csiaddons.openshift.io"
    resources:
      - "csiaddonsnodes"
      - "networkfences"
      - "reclaimspacecronjobs"
      - "reclaimspacejobs"
    verbs:
      - get
      - list
      - watch
      - patch
      - update
  - apiGroups:
    - operators.coreos.com
    resources:
    - clusterserviceversions
    - installplans
    - subscriptions
    verbs:
      - get
      - list
      - watch
      - patch
      - update
      - delete
  - apiGroups:
    - monitoring.coreos.com
    resources:
    - alertmanagers
    - alertmanagerconfigs
    - prometheuses
    - prometheusrules
    - servicemonitors
    - podmonitors
    verbs:
      - get
      - list
      - watch
      - patch
      - update
      - delete
  - apiGroups:
    - k8s.ovn.org
    resources:
    - egressfirewalls
    verbs:
    - get
    - list
    - watch
    - patch
    - update
  - apiGroups:
    - networking.k8s.io
    resources:
    - networkpolicies
    verbs:
    - get
    - list
    - watch
    - patch
    - update
  - apiGroups:
    - network.openshift.io
    resources:
    - egressnetworkpolicies
    verbs:
    - get
    - list
    - watch
    - patch
    - update
  - apiGroups:
    - coordination.k8s.io
    resources:
    - leases
    verbs:
    - get
    - list
    - watch
    - patch
    - update
