apiVersion: managed.openshift.io/v1alpha1
kind: SubjectPermission
metadata:
  name: backplane-mtsre-ocs-provider-admins
  namespace: openshift-rbac-permissions
spec:
  permissions:
  - allowFirst: true
    clusterRoleName: admin
    namespacesAllowedRegex: (^openshift-storage$)
  - allowFirst: true
    clusterRoleName: backplane-mtsre-ocs-provider-cr-admins
    namespacesAllowedRegex: (^openshift-storage$)
  - allowFirst: true
    clusterRoleName: backplane-mtsre-monitoring
    namespacesAllowedRegex: (^openshift-storage$)
  subjectKind: Group
  subjectName: system:serviceaccounts:openshift-backplane-mtsre
