apiVersion: managed.openshift.io/v1alpha1
kind: SubjectPermission
metadata:
  name: backplane-mtsre-ocs-provider
  namespace: openshift-rbac-permissions
spec:
  permissions:
  - clusterRoleName: admin
    namespacesAllowedRegex: (^openshift-storage$)
    namespacesDeniedRegex: openshift-backplane-cluster-admin
  - clusterRoleName: backplane-ocs-provider-cr-project
    namespacesAllowedRegex: (^openshift-storage$)
    namespacesDeniedRegex: openshift-backplane-cluster-admin
  - clusterRoleName: backplane-mtsre-monitoring-project
    namespacesAllowedRegex: (^openshift-storage$)
    namespacesDeniedRegex: openshift-backplane-cluster-admin
  subjectKind: Group
  subjectName: system:serviceaccounts:openshift-backplane-mtsre
