apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: backplane-tam
  namespace: openshift-monitoring
rules:
# TAM can portforward monitoring pods
- apiGroups:
  - ""
  resources:
  - pods/portforward
  verbs:
  - create
