apiVersion: hive.openshift.io/v1
kind: SelectorSyncSet
metadata:
  labels:
    managed.openshift.io/gitHash: ${IMAGE_TAG}
    managed.openshift.io/gitRepoName: ${REPO_NAME}
    managed.openshift.io/osd: 'true'
  name: crio-config
spec:
  clusterDeploymentSelector:
    matchLabels:
      api.openshift.com/managed: 'true'
    matchExpressions:
    - key: hive.openshift.io/version-major-minor
      operator: In
      values:
      - '4.8'
      - '4.9'
      - '4.10'
      - '4.11'
    - key: hive.openshift.io/version-major-minor-patch
      operator: NotIn
      values:
      - 4.8.2
      - 4.8.3
      - 4.8.4
      - 4.8.5
      - 4.8.9
      - 4.8.10
      - 4.8.11
      - 4.8.12
      - 4.8.13
      - 4.8.14
      - 4.8.15
      - 4.8.17
      - 4.8.18
      - 4.8.19
      - 4.8.20
      - 4.8.21
      - 4.8.22
      - 4.8.23
      - 4.8.24
      - 4.8.25
      - 4.8.26
      - 4.8.27
      - 4.8.28
      - 4.8.29
      - 4.8.31
      - 4.8.32
      - 4.8.33
      - 4.8.34
      - 4.9.0
      - 4.9.4
      - 4.9.5
      - 4.9.6
      - 4.9.7
      - 4.9.8
      - 4.9.9
      - 4.9.10
      - 4.9.11
      - 4.9.12
      - 4.9.13
      - 4.9.15
      - 4.9.17
      - 4.9.18
      - 4.9.19
      - 4.9.21
      - 4.9.22
      - 4.9.23
      - 4.9.24
      - 4.9.25
      - 4.10.3
      - 4.10.4
      - 4.10.5
      - 4.11.14
      - 4.11.15
      - 4.11.16
      - 4.11.17
      - 4.11.18
      - 4.11.19
      - 4.11.20
      - 4.11.21
      - 4.11.22
      - 4.11.23
      - 4.11.24
      - 4.11.25
      - 4.11.26
      - 4.11.27
      - 4.11.28
      - 4.11.29
      - 4.11.30
      - 4.11.31
      - 4.11.32
      - 4.11.33
      - 4.11.34
      - 4.11.35
      - 4.11.36
      - 4.11.37
      - 4.11.38
      - 4.11.39
      - 4.11.40
      - 4.11.41
      - 4.11.42
      - 4.11.43
      - 4.11.44
      - 4.11.45
      - 4.11.46
      - 4.11.47
      - 4.11.48
      - 4.11.49
      - 4.11.50
      - 4.11.51
      - 4.11.52
      - 4.11.53
      - 4.11.54
      - 4.11.55
      - 4.11.56
      - 4.11.57
      - 4.11.58
      - 4.11.59
      - 4.11.60
      - 4.11.61
      - 4.11.62
      - 4.11.63
      - 4.11.64
      - 4.11.65
      - 4.11.66
      - 4.11.67
      - 4.11.68
      - 4.11.69
      - 4.11.70
      - 4.11.71
      - 4.11.72
      - 4.11.73
      - 4.11.74
      - 4.11.75
      - 4.11.76
      - 4.11.77
      - 4.11.78
      - 4.11.79
      - 4.11.80
      - 4.11.81
      - 4.11.82
      - 4.11.83
      - 4.11.84
      - 4.11.85
      - 4.11.86
      - 4.11.87
      - 4.11.88
      - 4.11.89
      - 4.11.90
      - 4.11.91
      - 4.11.92
      - 4.11.93
      - 4.11.94
      - 4.11.95
      - 4.11.96
      - 4.11.97
      - 4.11.98
      - 4.11.99
  resourceApplyMode: Sync
  resources:
  - apiVersion: machineconfiguration.openshift.io/v1
    kind: ContainerRuntimeConfig
    metadata:
      name: custom-crio
    spec:
      machineConfigPoolSelector:
        matchExpressions:
        - key: pools.operator.machineconfiguration.openshift.io/worker
          operator: Exists
      containerRuntimeConfig:
        pidsLimit: 4096
