apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dedicated-admins-openshift-dns
  namespace: openshift-dns
subjects:
- kind: Group
  name: dedicated-admins
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dedicated-admins-openshift-dns
