apiVersion: managed.openshift.io/v1alpha1
kind: SubjectPermission
metadata:
  name: dedicated-admin-serviceaccounts-core-ns
  namespace: openshift-rbac-permissions
spec:
  subjectKind: Group
  subjectName: system:serviceaccounts:dedicated-admin
  permissions:
    -
      clusterRoleName: dedicated-admins-project
      namespacesAllowedRegex: "(^openshift-operators$|^openshift-operators-redhat$)"
      allowFirst: true
    -
      clusterRoleName: admin
      namespacesAllowedRegex: "(^openshift-operators$|^openshift-operators-redhat$)"
      allowFirst: true