apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: backplane-csm-mustgather
  namespace: openshift-backplane-managed-scripts
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:serviceaccounts:openshift-backplane-csm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: backplane-csm-pcap-collector
