apiVersion: ocmagent.managed.openshift.io/v1alpha1
kind: ManagedNotification
metadata:
  name: sre-managed-notifications
  namespace: openshift-ocm-agent-operator
spec:
  notifications:
    - activeBody: |-
        Your cluster requires you to take action as its ElasticSearch cluster logging deployment has been detected as reaching a high disk usage threshold. Red Hat SRE strongly recommends reducing application logging on your cluster to ensure logging continues to function. If logging disk consumption exceeds 95%, data will be at risk of becoming unavailable or lost and the stability of your ElasticSearch deployment may be impacted.
      name: LoggingVolumeFillingUp
      resendWait: 24
      resolvedBody: |-
        Your cluster's ElasticSearch deployment is detected as being at safe disk consumption levels and no additional action on this issue is required.
      severity: Info
      summary: "ElasticSearch reaching disk capacity"
    - activeBody: |-
        Your cluster requires you to take action. SRE has observed that there is more than one default Storage Class configured for your cluster. Please specify one default storage class for your persistent volume claims. Consult the documentation for details: https://docs.openshift.com/container-platform/latest/storage/understanding-persistent-storage.html#pvc-storage-class_understanding-persistent-storage
      name: MultipleDefaultStorageClasses
      resendWait: 24
      resolvedBody: |-
        Your cluster no longer has multiple default storage classes defined. No further action is required.
      severity: Info
      summary: "Multiple Default Storage Classes Configured"
    - activeBody: |-
        A user on your system has removed a platform protection webhook. This protection has already been automatically replaced, and no further action is required. Tampering with platform protections can endanger SLAs.
      name: NonSystemChangeValidationWebhookConfigurations # https://issues.redhat.com/browse/OSD-13558
      resendWait: 24
      severity: Error
      summary: "Platform protections removed by non-Red Hat user"
