deploymentMode: "SelectorSyncSet"
selectorSyncSet:
  matchExpressions:
  - key: hive.openshift.io/version-major-minor
    operator: In
    values: ["4.11", "4.12", "4.13", "4.14", "4.15"]
  - key: ext-managed.openshift.io/uwm-disabled
    operator: NotIn
    values: ["true"]
  - key: api.openshift.com/fedramp
    operator: NotIn
    values: ["true"]
  - key: ext-hypershift.openshift.io/cluster-type
    operator: NotIn
    values: ["management-cluster"]
