apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backplane-srep-admins-project
rules:
# SRE can get, list, and watch all resources
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
# SRE can evict pods
- apiGroups:
  - ""
  resources:
  - pods/eviction
  verbs:
  - create
# SRE can portforward pods
- apiGroups:
  - ""
  resources:
  - pods/portforward
  verbs:
  - create
  # SRE can run commands in pods
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - create
# SRE can manage jobs and builds
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - delete
  - deletecollection
  - create
- apiGroups:
  - build.openshift.io
  resources:
  - builds
  verbs:
  - delete
  - deletecollection
# SRE can use oc debug
- apiGroups:
  - ""
  resources:
  - pods
  - pods/attach
  verbs:
  - create
# SRE can delete pods
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - delete
  - deletecollection
# SRE can review pod security policies
- apiGroups:
  - security.openshift.io
  resources:
  - podsecuritypolicyreviews
  - podsecuritypolicyselfsubjectreviews
  - podsecuritypolicysubjectreviews
  verbs:
  - create
# SRE can review RBAC policies (i.e. oc adm policy who-can ...)
- apiGroups:
  - authorization.openshift.io
  resources:
  - localresourceaccessreviews
  - localsubjectaccessreviews
  verbs:
  - create
# SRE can manage Logging (ClusterLogging and ElasticSearch CRs)
- apiGroups:
  - logging.openshift.io
  resources:
  - '*'
  verbs:
  - '*'
# SRE can download backups, review logs, and create backup
- apiGroups:
  - velero.io
  resources:
  - backups
  verbs:
  - create
- apiGroups:
  - velero.io
  resources:
  - deletebackuprequests
  - downloadrequests
  - serverstatusrequests
  verbs:
  - '*'
# SRE can resize and delete pvcs
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - delete
  - patch
# SRE can scale apps
- apiGroups:
  - ""
  resources:
  - replicationcontrollers/scale
  verbs:
  - patch
- apiGroups:
  - apps
  resources:
  - deployments/scale
  - replicasets/scale
  - statefulsets/scale
  verbs:
  - patch
- apiGroups:
  - apps.openshift.io
  resources:
  - deploymentconfigs/scale
  verbs:
  - patch
# SRE can delete replicasets
- apiGroups:
  - ""
  resources:
  - replicasets
  verbs:
  - delete
  - deletecollection
# SRE can pause machinehealthchecks
- apiGroups:
  - machine.openshift.io
  resources:
  - machinehealthchecks
  verbs:
  - patch
# SRE can scale machinesets
- apiGroups:
  - machine.openshift.io
  resources:
  - machinesets/scale
  verbs:
  - patch
# SRE can scale prometheuses
- apiGroups:
  - monitoring.coreos.com
  resources:
  - prometheuses
  verbs:
  - patch
# SRE can delete upgradeconfigs
- apiGroups:
  - upgrade.managed.openshift.io
  resources:
  - upgradeconfigs
  verbs:
  - delete
# SRE can delete csv, installplans, and subscriptions
- apiGroups:
  - operators.coreos.com
  resources:
  - clusterserviceversions
  - installplans
  - subscriptions
  verbs:
  - delete
