apiVersion: managed.openshift.io/v1alpha1
kind: SubjectPermission
metadata:
  name: backplane-srep-impersonate
  namespace: openshift-rbac-permissions
spec:
  clusterPermissions:
  - backplane-srep-admins-cluster
  - backplane-srep-readers-cluster
  permissions:
  - allowFirst: true
    clusterRoleName: backplane-srep-admins-project
    namespacesAllowedRegex: "(^kube$|^kube-.*|^openshift$|^openshift-.*|^default$|^redhat-.*)"
    namespacesDeniedRegex: openshift-backplane-cluster-admin
  subjectKind: Group
  subjectName: system:backplane:srep
