deploymentMode: "SelectorSyncSet"
selectorSyncSet:
  matchExpressions:
  - key: hive.openshift.io/version-major-minor-patch
    operator: In
    values: ["4.7.24", "4.7.25", "4.7.26", "4.7.27", "4.7.28", "4.8.5", "4.8.6", "4.8.7", "4.8.8", "4.8.9"]
